#!/usr/bin/env ruby
# pretty prints json input from stdin and rewrites unix timestamps contained therein to human readable strings
require 'json'

def rewrite_dates(obj)
    if obj.kind_of? Array
        obj.each{|elem| rewrite_dates(elem)}
    elsif obj.kind_of? Hash
        obj.each_pair{|k, v|
            if v.kind_of?(Numeric) && k=~/date/i
                # if date is unreasonably far in the future, it's probably millisecond precision instead of seconds
                v/=1000 if v>134027890200
                obj[k] = Time.at(v)
            else
                rewrite_dates(v)
            end
        }
    end
end

obj = JSON.restore(STDIN)
rewrite_dates(obj)
print JSON.pretty_generate(obj)
